version: "3"
services:
  atcoder-introduction-to-heuristic-contest:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project/src
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    container_name: atcoder-introduction-to-heuristic-contest
    tty: true
